### ISSUE TITLE
No new releases triggered due to workflows being automatically disabled because of repo inactivity

### ISSUE THREAD

**Issue by alexsporn** [jefflessard/plex-alpine#1]
The `Scan` workflow is disabled due to inactivity

```
This scheduled workflow is disabled because there hasn't been activity in this repository for at least 60 days. Enable this workflow to resume scheduled runs.
```

This is the reason why `1.32.3` has not been released yet.

**Comment by jefflessard** [comment]
I have re-enabled the Scan workflow and manually started the 1.32.3 Docker build

**Comment by alexsporn** [comment]
@jefflessard this seems to have happened again. The Scan workflow says `This scheduled workflow is disabled because there hasn't been activity in this repository for at least 60 days. Enable this workflow to resume scheduled runs`

**Comment by jefflessard** [comment]
Please use linuxserver/plex Docker Image. Plex now works with AMD GPUs.
